import { Request, Response } from 'express';
import Channels from '../database/models/Channels';
import { getAllChannels, getByIdChannels, createChannels, sendMessageChannel, deleteChannelById } from '../services/channels.service';

async function getAll(req: Request, res: Response) {
  const channels = await getAllChannels();
  res.status(200).json(channels);
}

async function getById(req: Request, res: Response) {
  const channel = await getByIdChannels(req.params.id);

  if (channel) {
    res.status(200).json(channel);
  } else {
    res.status(404).send();
  }
}

async function create(req: Request, res: Response) {
  // if all atributes are found in the request
  const modelAttributes = Channels.rawAttributes;
  for (const key in modelAttributes) {
    if ('_autoGenerated' in modelAttributes[key] === false) {
      if (key in req.body === false && key != "id") {
        res.status(500).send();
        return;
      }
    }
  }

  const channel = await createChannels(req.body);
  res.status(200).json(channel);
}

async function sendMessage(req: Request, res: Response) {
  if ("type" in req.body && "value" in req.body) {
    const channels = await sendMessageChannel(req.params.id, req.body);
    res.status(200).json({message: channels.data});
  } else {
    res.status(500).json({message: 'Message not sended'});
  }
}

function deleteChannel(req: Request, res: Response) {
  deleteChannelById(req.params.id)
    .then((data) => {
      if (!data.err) {
        res.status(200).json({message: data.data});
      }
    })
    .catch((error) => {
      res.status(500).json({message: 'Request Error'});
    })
}


export {
  getAll, getById, create,
  sendMessage, deleteChannel,
}
